#!/usr/bin/env python3
"""Generate or verify committed JSON Schemas from canonical Pydantic models."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Type

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pydantic import BaseModel  # noqa: E402

from agentsec.approval import ApprovalToken  # noqa: E402
from agentsec.authority import AuthorityGrant  # noqa: E402
from agentsec.contracts import (  # noqa: E402
    AgentEvent,
    AiAnalystRun,
    AnalystAlternative,
    AnalystClaim,
    AnalystDisagreement,
    AnalystEvidenceItem,
    AnalystFeedback,
    AnalystHealthSummary,
    AnalystRoleRequest,
    AnalystRoleResult,
    AnalystToolReceipt,
    ClaimValidationResult,
    EventProcessingResult,
    EnrichmentSnapshot,
    Finding,
    Judgment,
    JudgmentContradiction,
    JudgmentValidationIssue,
    JudgmentValidationReport,
    MandatoryEvidenceCheck,
    ModelVerdict,
    ModelVerdictValidation,
    PipelineResult,
    SecurityAlert,
    TriageAssessment,
)
from agentsec.ingestion import LedgerVerification  # noqa: E402
from agentsec.evaluation import (  # noqa: E402
    AblationReport,
    EvaluationReleaseManifest,
    EvaluationReport,
)
from agentsec.continuous_evaluation import (  # noqa: E402
    BlindEvaluationCase,
    ContinuousEvaluationMetrics,
    ContinuousEvaluationReport,
    EvaluationAuditEntry,
    EvaluationBaseline,
    EvaluationBaselineApprovalRequest,
    EvaluationCandidateMetadata,
    EvaluationCatalog,
    EvaluationCaseResult,
    EvaluationDataset,
    EvaluationDatasetManifest,
    EvaluationFeedbackPage,
    EvaluationFeedbackPromotionRequest,
    EvaluationFeedbackProposal,
    EvaluationFeedbackProposalRequest,
    EvaluationFeedbackReviewRequest,
    EvaluationGateDecision,
    EvaluationHealth,
    EvaluationPrediction,
    EvaluationPrincipal,
    EvaluationRunPage,
    EvaluationRunRecord,
    EvaluationRunRequest,
    EvaluationThresholdPolicy,
)
from agentsec.administration import (  # noqa: E402
    AccessReviewRecord,
    AdministrationAuditCheckpoint,
    AdministrationAuditEntry,
    AdministrationAuditVerification,
    AdministrationHealth,
    AdministrationPrincipal,
    AdministrationSnapshot,
    HumanIdentityRecord,
    ManagedKeyRecord,
    RecoveryDrillRecord,
    ServiceLevelMeasurement,
    ServiceLevelObjective,
    SignedIdentityAssertion,
    SupplyChainAttestation,
    TenantSecurityPolicy,
    WorkloadIdentityRecord,
)
from agentsec.model_registry import ModelRegistry  # noqa: E402
from agentsec.privacy import ModelEvidenceBundle, SocFindingExport  # noqa: E402
from agentsec.provenance import ProvenanceRecord  # noqa: E402
from agentsec.providers import (  # noqa: E402
    AnalystProviderPayload,
    ProviderCallRecord,
    ProviderVerdictPayload,
)
from agentsec.synthetic import ScenarioDefinition, WorkflowRun  # noqa: E402
from agentsec.service import AuthorizationResponse  # noqa: E402
from agentsec.abom import AbomDiff, AbomManifest  # noqa: E402
from agentsec.checkpoints import CheckpointVerification, LedgerCheckpoint  # noqa: E402
from agentsec.graph import (  # noqa: E402
    AttackPathResult,
    BlastRadiusResult,
    CausalPath,
    GraphEdgeInput,
    GraphIngestResult,
    GraphNodeInput,
    GraphPrincipal,
    ReachabilityResult,
    ReachableNode,
    SecurityGraphEdge,
    SecurityGraphNode,
    SecurityGraphSnapshot,
    SecurityGraphSummary,
    WeightedAttackPath,
)
from agentsec.adapters import FrameworkToolProposal  # noqa: E402
from agentsec.observation import ObservationFinding  # noqa: E402
from agentsec.incidents import (  # noqa: E402
    IncidentDetail,
    IncidentListResponse,
    IncidentTransitionRequest,
)
from agentsec.splunk import SplunkDeadLetter, SplunkExportReceipt  # noqa: E402
from agentsec.telemetry import (  # noqa: E402
    CaptureReceipt,
    TelemetryBatchResult,
    TelemetryContext,
    TelemetryEnvelope,
    TelemetryInput,
    TelemetrySourceHealth,
)
from agentsec.gateway import (  # noqa: E402
    GatewayBatchResponse,
    GatewayReceipt,
    GatewaySourceHealth,
    QueueSummary,
    WorkloadPrincipal,
)
from agentsec.datamodel import (  # noqa: E402
    ActionRecord,
    AlertRecord,
    CanonicalBundle,
    CanonicalRecordEnvelope,
    EntityRecord,
    EventRecord,
    EvidenceRecord,
    FindingRecord,
    IncidentRecord,
    InvestigationRecord,
    JudgmentRecord,
)
from agentsec.storage import (  # noqa: E402
    BackupManifest,
    CheckpointResult,
    ProtectedEvidenceBlob,
    RecordCommitReceipt,
    RetentionPolicy,
    RetentionResult,
    StorageCheckpoint,
    StorageVerification,
)
from agentsec.search import (  # noqa: E402
    AggregationResult,
    EvidencePivot,
    SavedHunt,
    SearchHit,
    SearchIndexStats,
    SearchPage,
    SearchPrincipal,
    SearchRequest,
)
from agentsec.inventory import (  # noqa: E402
    ComponentPermission,
    ComponentUpsert,
    ConfigurationRevision,
    DiscoveryResult,
    InventoryComponent,
    InventoryDetail,
    InventoryObservation,
    InventoryPage,
    InventoryPrincipal,
    InventoryRelationship,
    InventoryRiskRollup,
    InventorySummary,
)
from agentsec.posture import (  # noqa: E402
    PostureCheckDefinition,
    PostureCheckRecord,
    PostureException,
    PostureFinding,
    PostureFindingDetail,
    PostureFindingPage,
    PosturePrincipal,
    PostureScanResult,
    PostureSummary,
    PostureTrendPoint,
    PostureTrendSeries,
)
from agentsec.detection import (  # noqa: E402
    DetectionBatchResult,
    DetectionCondition,
    DetectionExecutionRecord,
    DetectionPredicate,
    DetectionPrincipal,
    DetectionRuleDefinition,
    DetectionRuleHealth,
    DetectionRuleRecord,
    SemanticDetectionVerdict,
)
from agentsec.content import (  # noqa: E402
    ContentHealthSummary,
    ContentPackEntry,
    ContentPrincipal,
    RuleBacktestResult,
    RuleContentRecord,
    RuleTestSuite,
    RuleValidationResult,
    SignedContentPack,
)
from agentsec.behavior import (  # noqa: E402
    BehaviorBaseline,
    BehaviorDriftSummary,
    BehaviorEventAssessment,
    BehaviorFeatureVector,
    BehaviorHealthSummary,
    BehaviorPrincipal,
    BehaviorRiskFactor,
    BehaviorTuningConfig,
    BehaviorTuningInput,
    EntityBehaviorScore,
)
from agentsec.correlation import (  # noqa: E402
    AttackSequenceStep,
    CorrelatedIncident,
    CorrelationAuditEntry,
    CorrelationCandidate,
    CorrelationDecision,
    CorrelationHealth,
    CorrelationPrincipal,
    CorrelationSignal,
    CorrelationSplitResult,
    IncidentFindingLink,
    SuppressionRule,
)
from agentsec.enrichment import (  # noqa: E402
    EnrichmentConnectorHealth,
    EnrichmentConnectorPayload,
    EnrichmentConnectorRequest,
    EnrichmentConnectorSpec,
    EnrichmentHealthSummary,
    EnrichmentPrincipal,
    EnrichmentRuntimeConfig,
    HttpEnrichmentConnectorConfig,
)
from agentsec.analyst import (  # noqa: E402
    AnalystPrincipal,
    RecordedAnalystConfiguration,
    RecordedRoleTemplate,
)
from agentsec.model_gateway import (  # noqa: E402
    ModelCallReceipt,
    ModelGatewayAuditEntry,
    ModelGatewayConfiguration,
    ModelGatewayHealthSummary,
    ModelGatewayPrincipal,
    ModelQualification,
    ModelRouteRevision,
    PromptConfiguration,
    PromptVersion,
    ProviderHealth,
    QualificationMetrics,
    RouteConfiguration,
    SecretConfiguration,
    SecretVersionMetadata,
)
from agentsec.cases import (  # noqa: E402
    CaseAssignmentRequest,
    CaseAttachment,
    CaseAttachmentRequest,
    CaseAttachmentScanRequest,
    CaseAuditEntry,
    CaseComment,
    CaseCommentRequest,
    CaseDetail,
    CaseHealth,
    CaseLifecycleRequest,
    CasePage,
    CasePrincipal,
    CaseRecord,
    CaseRelationship,
    CaseRelationshipRequest,
    CaseReview,
    CaseReviewRequest,
    CaseTask,
    CaseTaskCreateRequest,
    CaseTaskTransitionRequest,
    CaseTeam,
    CaseTeamCreateRequest,
)
from agentsec.notifications import (  # noqa: E402
    ConnectorResult,
    DeliveryBatchResult,
    NotificationAcknowledgeRequest,
    NotificationAttempt,
    NotificationAuditEntry,
    NotificationDelivery,
    NotificationDestination,
    NotificationDestinationPage,
    NotificationDestinationStatus,
    NotificationDetail,
    NotificationHealth,
    NotificationMessage,
    NotificationPage,
    NotificationPolicy,
    NotificationPrincipal,
    NotificationProcessRequest,
    NotificationRecord,
    NotificationRedriveRequest,
    NotificationRoute,
    NotificationTemplate,
    OnCallSchedule,
    ProviderAcknowledgeRequest,
)
from agentsec.response import (  # noqa: E402
    PlaybookStepDefinition,
    PlaybookTrigger,
    ResponseApproval,
    ResponseApprovalRequest,
    ResponseAttempt,
    ResponseAuditEntry,
    ResponseAutomationPolicy,
    ResponseConnectorRequest,
    ResponseConnectorResult,
    ResponseConnectorSpec,
    ResponseConnectorStatus,
    ResponseControl,
    ResponseEmptyRequest,
    ResponseExecution,
    ResponseExecutionDetail,
    ResponseExecutionPage,
    ResponseHealth,
    ResponseKillSwitchRequest,
    ResponseMutationRequest,
    ResponsePlaybookActionRequest,
    ResponsePlaybookCreateRequest,
    ResponsePlaybookDefinition,
    ResponsePlaybookPage,
    ResponsePlaybookRecord,
    ResponsePrincipal,
    ResponseStepPlan,
    ResponseVerificationResult,
)
from agentsec.integrations import (  # noqa: E402
    ConnectorOutcome,
    ExternalApiAccessPolicy,
    ExternalApiCapabilities,
    ExternalApiCapability,
    ExternalApiClientSpec,
    ExternalApiPrincipal,
    ExternalEventPage,
    ExternalSecurityEvent,
    IntegrationAttempt,
    IntegrationAuditEntry,
    IntegrationDelivery,
    IntegrationDeliveryDetail,
    IntegrationDeliveryPage,
    IntegrationDestinationSpec,
    IntegrationDestinationStatus,
    IntegrationHealth,
    IntegrationPolicy,
    IntegrationPrincipal,
    IntegrationProcessRequest,
    IntegrationProcessResult,
    IntegrationRedriveRequest,
    IntegrationTransportResponse,
)
from agentsec.simulation import (  # noqa: E402
    SimulationAuditEntry,
    SimulationCatalog,
    SimulationHealth,
    SimulationImportRequest,
    SimulationImportResult,
    SimulationModeResult,
    SimulationMutationRequest,
    SimulationPrincipal,
    SimulationReplayRequest,
    SimulationRun,
    SimulationRunPage,
    SimulationRunRequest,
    SimulationSandboxReceipt,
    SimulationScenario,
    SimulationScenarioDraft,
    SimulationScenarioPage,
    SimulationScenarioStep,
    SimulationStepResult,
    SimulationVariantProfile,
)


MODELS: Dict[str, Type[BaseModel]] = {
    "action-event": AgentEvent,
    "security-alert": SecurityAlert,
    "model-verdict": ModelVerdict,
    "model-verdict-validation": ModelVerdictValidation,
    "judgment": Judgment,
    "finding": Finding,
    "pipeline-result": PipelineResult,
    "event-processing-result": EventProcessingResult,
    "approval-token": ApprovalToken,
    "authority-grant": AuthorityGrant,
    "provenance-record": ProvenanceRecord,
    "ledger-verification": LedgerVerification,
    "scenario-definition": ScenarioDefinition,
    "workflow-run": WorkflowRun,
    "evaluation-report": EvaluationReport,
    "ablation-report": AblationReport,
    "evaluation-release-manifest": EvaluationReleaseManifest,
    "continuous-evaluation-blind-case": BlindEvaluationCase,
    "continuous-evaluation-metrics": ContinuousEvaluationMetrics,
    "continuous-evaluation-report": ContinuousEvaluationReport,
    "continuous-evaluation-audit-entry": EvaluationAuditEntry,
    "continuous-evaluation-baseline": EvaluationBaseline,
    "continuous-evaluation-baseline-approval-request": EvaluationBaselineApprovalRequest,
    "continuous-evaluation-candidate": EvaluationCandidateMetadata,
    "continuous-evaluation-catalog": EvaluationCatalog,
    "continuous-evaluation-case-result": EvaluationCaseResult,
    "continuous-evaluation-dataset": EvaluationDataset,
    "continuous-evaluation-dataset-manifest": EvaluationDatasetManifest,
    "continuous-evaluation-feedback-page": EvaluationFeedbackPage,
    "continuous-evaluation-feedback-promotion-request": EvaluationFeedbackPromotionRequest,
    "continuous-evaluation-feedback-proposal": EvaluationFeedbackProposal,
    "continuous-evaluation-feedback-proposal-request": EvaluationFeedbackProposalRequest,
    "continuous-evaluation-feedback-review-request": EvaluationFeedbackReviewRequest,
    "continuous-evaluation-gate": EvaluationGateDecision,
    "continuous-evaluation-health": EvaluationHealth,
    "continuous-evaluation-prediction": EvaluationPrediction,
    "continuous-evaluation-principal": EvaluationPrincipal,
    "continuous-evaluation-run-page": EvaluationRunPage,
    "continuous-evaluation-run-record": EvaluationRunRecord,
    "continuous-evaluation-run-request": EvaluationRunRequest,
    "continuous-evaluation-threshold-policy": EvaluationThresholdPolicy,
    "administration-access-review": AccessReviewRecord,
    "administration-audit-checkpoint": AdministrationAuditCheckpoint,
    "administration-audit-entry": AdministrationAuditEntry,
    "administration-audit-verification": AdministrationAuditVerification,
    "administration-health": AdministrationHealth,
    "administration-principal": AdministrationPrincipal,
    "administration-snapshot": AdministrationSnapshot,
    "administration-human-identity": HumanIdentityRecord,
    "administration-managed-key": ManagedKeyRecord,
    "administration-recovery-drill": RecoveryDrillRecord,
    "administration-slo-measurement": ServiceLevelMeasurement,
    "administration-slo-objective": ServiceLevelObjective,
    "administration-signed-identity-assertion": SignedIdentityAssertion,
    "administration-supply-chain-attestation": SupplyChainAttestation,
    "administration-tenant-security-policy": TenantSecurityPolicy,
    "administration-workload-identity": WorkloadIdentityRecord,
    "model-registry": ModelRegistry,
    "model-evidence-bundle": ModelEvidenceBundle,
    "soc-finding-export": SocFindingExport,
    "provider-call-record": ProviderCallRecord,
    "provider-verdict-payload": ProviderVerdictPayload,
    "authorization-response": AuthorizationResponse,
    "abom-manifest": AbomManifest,
    "abom-diff": AbomDiff,
    "ledger-checkpoint": LedgerCheckpoint,
    "checkpoint-verification": CheckpointVerification,
    "causal-path": CausalPath,
    "graph-principal": GraphPrincipal,
    "graph-node-input": GraphNodeInput,
    "graph-edge-input": GraphEdgeInput,
    "graph-node": SecurityGraphNode,
    "graph-edge": SecurityGraphEdge,
    "graph-snapshot": SecurityGraphSnapshot,
    "graph-ingest-result": GraphIngestResult,
    "graph-weighted-attack-path": WeightedAttackPath,
    "graph-attack-path-result": AttackPathResult,
    "graph-reachable-node": ReachableNode,
    "graph-reachability-result": ReachabilityResult,
    "graph-blast-radius-result": BlastRadiusResult,
    "graph-summary": SecurityGraphSummary,
    "framework-tool-proposal": FrameworkToolProposal,
    "observation-finding": ObservationFinding,
    "incident-detail": IncidentDetail,
    "incident-list-response": IncidentListResponse,
    "incident-transition-request": IncidentTransitionRequest,
    "enrichment-snapshot": EnrichmentSnapshot,
    "triage-assessment": TriageAssessment,
    "splunk-export-receipt": SplunkExportReceipt,
    "splunk-dead-letter": SplunkDeadLetter,
    "telemetry-context": TelemetryContext,
    "telemetry-input": TelemetryInput,
    "telemetry-envelope": TelemetryEnvelope,
    "telemetry-capture-receipt": CaptureReceipt,
    "telemetry-source-health": TelemetrySourceHealth,
    "telemetry-batch-result": TelemetryBatchResult,
    "gateway-workload-principal": WorkloadPrincipal,
    "gateway-ingestion-receipt": GatewayReceipt,
    "gateway-batch-response": GatewayBatchResponse,
    "gateway-source-health": GatewaySourceHealth,
    "gateway-queue-summary": QueueSummary,
    "canonical-event": EventRecord,
    "canonical-evidence": EvidenceRecord,
    "canonical-entity": EntityRecord,
    "canonical-alert": AlertRecord,
    "canonical-finding": FindingRecord,
    "canonical-incident": IncidentRecord,
    "canonical-investigation": InvestigationRecord,
    "canonical-judgment": JudgmentRecord,
    "canonical-action": ActionRecord,
    "canonical-record-envelope": CanonicalRecordEnvelope,
    "canonical-bundle": CanonicalBundle,
    "storage-record-commit-receipt": RecordCommitReceipt,
    "storage-verification": StorageVerification,
    "storage-protected-evidence-blob": ProtectedEvidenceBlob,
    "storage-checkpoint": StorageCheckpoint,
    "storage-checkpoint-result": CheckpointResult,
    "storage-retention-policy": RetentionPolicy,
    "storage-retention-result": RetentionResult,
    "storage-backup-manifest": BackupManifest,
    "search-principal": SearchPrincipal,
    "search-request": SearchRequest,
    "search-hit": SearchHit,
    "search-page": SearchPage,
    "search-aggregation-result": AggregationResult,
    "search-saved-hunt": SavedHunt,
    "search-evidence-pivot": EvidencePivot,
    "search-index-stats": SearchIndexStats,
    "inventory-principal": InventoryPrincipal,
    "inventory-component-permission": ComponentPermission,
    "inventory-component-upsert": ComponentUpsert,
    "inventory-component": InventoryComponent,
    "inventory-detail": InventoryDetail,
    "inventory-configuration-revision": ConfigurationRevision,
    "inventory-observation": InventoryObservation,
    "inventory-discovery-result": DiscoveryResult,
    "inventory-relationship": InventoryRelationship,
    "inventory-risk-rollup": InventoryRiskRollup,
    "inventory-summary": InventorySummary,
    "inventory-page": InventoryPage,
    "posture-principal": PosturePrincipal,
    "posture-check-definition": PostureCheckDefinition,
    "posture-check-record": PostureCheckRecord,
    "posture-finding": PostureFinding,
    "posture-finding-detail": PostureFindingDetail,
    "posture-finding-page": PostureFindingPage,
    "posture-exception": PostureException,
    "posture-scan-result": PostureScanResult,
    "posture-summary": PostureSummary,
    "posture-trend-point": PostureTrendPoint,
    "posture-trend-series": PostureTrendSeries,
    "detection-principal": DetectionPrincipal,
    "detection-condition": DetectionCondition,
    "detection-predicate": DetectionPredicate,
    "detection-rule-definition": DetectionRuleDefinition,
    "detection-rule-record": DetectionRuleRecord,
    "detection-semantic-verdict": SemanticDetectionVerdict,
    "detection-execution-record": DetectionExecutionRecord,
    "detection-batch-result": DetectionBatchResult,
    "detection-rule-health": DetectionRuleHealth,
    "content-principal": ContentPrincipal,
    "content-rule-test-suite": RuleTestSuite,
    "content-rule-validation-result": RuleValidationResult,
    "content-rule-backtest-result": RuleBacktestResult,
    "content-rule-record": RuleContentRecord,
    "content-pack-entry": ContentPackEntry,
    "content-signed-pack": SignedContentPack,
    "content-health-summary": ContentHealthSummary,
    "behavior-principal": BehaviorPrincipal,
    "behavior-feature-vector": BehaviorFeatureVector,
    "behavior-risk-factor": BehaviorRiskFactor,
    "behavior-entity-score": EntityBehaviorScore,
    "behavior-event-assessment": BehaviorEventAssessment,
    "behavior-baseline": BehaviorBaseline,
    "behavior-tuning-input": BehaviorTuningInput,
    "behavior-tuning-config": BehaviorTuningConfig,
    "behavior-drift-summary": BehaviorDriftSummary,
    "behavior-health-summary": BehaviorHealthSummary,
    "correlation-principal": CorrelationPrincipal,
    "correlation-signal": CorrelationSignal,
    "correlation-finding-link": IncidentFindingLink,
    "correlation-attack-sequence-step": AttackSequenceStep,
    "correlation-audit-entry": CorrelationAuditEntry,
    "correlated-incident": CorrelatedIncident,
    "correlation-candidate": CorrelationCandidate,
    "correlation-decision": CorrelationDecision,
    "correlation-suppression-rule": SuppressionRule,
    "correlation-health": CorrelationHealth,
    "correlation-split-result": CorrelationSplitResult,
    "enrichment-principal": EnrichmentPrincipal,
    "enrichment-connector-spec": EnrichmentConnectorSpec,
    "enrichment-connector-request": EnrichmentConnectorRequest,
    "enrichment-connector-payload": EnrichmentConnectorPayload,
    "enrichment-connector-health": EnrichmentConnectorHealth,
    "enrichment-health-summary": EnrichmentHealthSummary,
    "enrichment-http-connector-config": HttpEnrichmentConnectorConfig,
    "enrichment-runtime-config": EnrichmentRuntimeConfig,
    "analyst-principal": AnalystPrincipal,
    "analyst-evidence-item": AnalystEvidenceItem,
    "analyst-alternative": AnalystAlternative,
    "analyst-claim": AnalystClaim,
    "analyst-role-request": AnalystRoleRequest,
    "analyst-role-result": AnalystRoleResult,
    "analyst-tool-receipt": AnalystToolReceipt,
    "analyst-disagreement": AnalystDisagreement,
    "judgment-mandatory-evidence-check": MandatoryEvidenceCheck,
    "judgment-claim-validation-result": ClaimValidationResult,
    "judgment-contradiction": JudgmentContradiction,
    "judgment-validation-issue": JudgmentValidationIssue,
    "judgment-validation-report": JudgmentValidationReport,
    "ai-analyst-run": AiAnalystRun,
    "analyst-feedback": AnalystFeedback,
    "analyst-health-summary": AnalystHealthSummary,
    "analyst-recorded-role-template": RecordedRoleTemplate,
    "analyst-recorded-configuration": RecordedAnalystConfiguration,
    "model-gateway-principal": ModelGatewayPrincipal,
    "model-gateway-prompt-version": PromptVersion,
    "model-gateway-secret-version-metadata": SecretVersionMetadata,
    "model-gateway-route-revision": ModelRouteRevision,
    "model-gateway-qualification-metrics": QualificationMetrics,
    "model-gateway-qualification": ModelQualification,
    "model-gateway-call-receipt": ModelCallReceipt,
    "model-gateway-provider-health": ProviderHealth,
    "model-gateway-health-summary": ModelGatewayHealthSummary,
    "model-gateway-audit-entry": ModelGatewayAuditEntry,
    "model-gateway-prompt-configuration": PromptConfiguration,
    "model-gateway-secret-configuration": SecretConfiguration,
    "model-gateway-route-configuration": RouteConfiguration,
    "model-gateway-configuration": ModelGatewayConfiguration,
    "analyst-provider-payload": AnalystProviderPayload,
    "case-principal": CasePrincipal,
    "case-team": CaseTeam,
    "case-record": CaseRecord,
    "case-comment": CaseComment,
    "case-task": CaseTask,
    "case-attachment": CaseAttachment,
    "case-relationship": CaseRelationship,
    "case-review": CaseReview,
    "case-audit-entry": CaseAuditEntry,
    "case-detail": CaseDetail,
    "case-page": CasePage,
    "case-health": CaseHealth,
    "case-assignment-request": CaseAssignmentRequest,
    "case-comment-request": CaseCommentRequest,
    "case-task-create-request": CaseTaskCreateRequest,
    "case-task-transition-request": CaseTaskTransitionRequest,
    "case-attachment-request": CaseAttachmentRequest,
    "case-attachment-scan-request": CaseAttachmentScanRequest,
    "case-relationship-request": CaseRelationshipRequest,
    "case-lifecycle-request": CaseLifecycleRequest,
    "case-review-request": CaseReviewRequest,
    "case-team-create-request": CaseTeamCreateRequest,
    "notification-principal": NotificationPrincipal,
    "notification-destination": NotificationDestination,
    "notification-on-call-schedule": OnCallSchedule,
    "notification-template": NotificationTemplate,
    "notification-route": NotificationRoute,
    "notification-policy": NotificationPolicy,
    "notification-message": NotificationMessage,
    "notification-record": NotificationRecord,
    "notification-delivery": NotificationDelivery,
    "notification-attempt": NotificationAttempt,
    "notification-audit-entry": NotificationAuditEntry,
    "notification-detail": NotificationDetail,
    "notification-page": NotificationPage,
    "notification-health": NotificationHealth,
    "notification-destination-status": NotificationDestinationStatus,
    "notification-destination-page": NotificationDestinationPage,
    "notification-delivery-batch-result": DeliveryBatchResult,
    "notification-acknowledge-request": NotificationAcknowledgeRequest,
    "notification-provider-acknowledge-request": ProviderAcknowledgeRequest,
    "notification-process-request": NotificationProcessRequest,
    "notification-redrive-request": NotificationRedriveRequest,
    "notification-connector-result": ConnectorResult,
    "response-principal": ResponsePrincipal,
    "response-connector-spec": ResponseConnectorSpec,
    "response-playbook-trigger": PlaybookTrigger,
    "response-playbook-step-definition": PlaybookStepDefinition,
    "response-playbook-definition": ResponsePlaybookDefinition,
    "response-automation-policy": ResponseAutomationPolicy,
    "response-playbook-record": ResponsePlaybookRecord,
    "response-step-plan": ResponseStepPlan,
    "response-execution": ResponseExecution,
    "response-approval": ResponseApproval,
    "response-attempt": ResponseAttempt,
    "response-audit-entry": ResponseAuditEntry,
    "response-control": ResponseControl,
    "response-connector-status": ResponseConnectorStatus,
    "response-execution-detail": ResponseExecutionDetail,
    "response-execution-page": ResponseExecutionPage,
    "response-playbook-page": ResponsePlaybookPage,
    "response-health": ResponseHealth,
    "response-mutation-request": ResponseMutationRequest,
    "response-approval-request": ResponseApprovalRequest,
    "response-kill-switch-request": ResponseKillSwitchRequest,
    "response-playbook-create-request": ResponsePlaybookCreateRequest,
    "response-playbook-action-request": ResponsePlaybookActionRequest,
    "response-empty-request": ResponseEmptyRequest,
    "response-connector-request": ResponseConnectorRequest,
    "response-connector-result": ResponseConnectorResult,
    "response-verification-result": ResponseVerificationResult,
    "integration-principal": IntegrationPrincipal,
    "integration-destination-spec": IntegrationDestinationSpec,
    "integration-policy": IntegrationPolicy,
    "external-security-event": ExternalSecurityEvent,
    "external-event-page": ExternalEventPage,
    "integration-destination-status": IntegrationDestinationStatus,
    "integration-attempt": IntegrationAttempt,
    "integration-delivery": IntegrationDelivery,
    "integration-delivery-detail": IntegrationDeliveryDetail,
    "integration-delivery-page": IntegrationDeliveryPage,
    "integration-health": IntegrationHealth,
    "integration-audit-entry": IntegrationAuditEntry,
    "external-api-capability": ExternalApiCapability,
    "external-api-capabilities": ExternalApiCapabilities,
    "external-api-client-spec": ExternalApiClientSpec,
    "external-api-access-policy": ExternalApiAccessPolicy,
    "external-api-principal": ExternalApiPrincipal,
    "integration-process-request": IntegrationProcessRequest,
    "integration-redrive-request": IntegrationRedriveRequest,
    "integration-process-result": IntegrationProcessResult,
    "integration-transport-response": IntegrationTransportResponse,
    "integration-connector-outcome": ConnectorOutcome,
    "simulation-principal": SimulationPrincipal,
    "simulation-variant-profile": SimulationVariantProfile,
    "simulation-scenario-step": SimulationScenarioStep,
    "simulation-scenario-draft": SimulationScenarioDraft,
    "simulation-scenario": SimulationScenario,
    "simulation-scenario-page": SimulationScenarioPage,
    "simulation-mutation-request": SimulationMutationRequest,
    "simulation-import-request": SimulationImportRequest,
    "simulation-import-result": SimulationImportResult,
    "simulation-run-request": SimulationRunRequest,
    "simulation-replay-request": SimulationReplayRequest,
    "simulation-sandbox-receipt": SimulationSandboxReceipt,
    "simulation-step-result": SimulationStepResult,
    "simulation-mode-result": SimulationModeResult,
    "simulation-run": SimulationRun,
    "simulation-run-page": SimulationRunPage,
    "simulation-audit-entry": SimulationAuditEntry,
    "simulation-health": SimulationHealth,
    "simulation-catalog": SimulationCatalog,
}


def render(model: Type[BaseModel]) -> str:
    return json.dumps(model.model_json_schema(), indent=2, sort_keys=True) + "\n"


def generate(output_dir: Path, check: bool) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    failures = []
    expected_names = set()
    for name, model in MODELS.items():
        path = output_dir / (name + ".schema.json")
        expected_names.add(path.name)
        expected = render(model)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                failures.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(expected, encoding="utf-8")

    extras = {
        path.name for path in output_dir.glob("*.schema.json") if path.name not in expected_names
    }
    if check and extras:
        failures.extend(str(output_dir / name) for name in sorted(extras))
    if failures:
        print("schema drift detected:")
        for failure in failures:
            print("- %s" % failure)
        return 1
    print("verified %d generated schemas" % len(MODELS))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=ROOT / "schemas" / "generated")
    args = parser.parse_args()
    return generate(args.output, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
